### ISSUE TITLE
Register devices

### ISSUE THREAD

**Issue by jboretsky** [ChoralCloud/ChoralWeb#12]
We need a way of registering devices. We would probably just need a button you can click that would generate an ID (based on current time? or just a counter?).

A user would later use that ID and send it in their HTTP Requests from their sensors.

**Comment by jboretsky** [comment]
We should also allow users to associate a name with the device they register.

**Comment by ecuellog** [comment]
- Device registration works, adds new choral to database and outputs the new id to the user. 
***I added a return statement to the choral.createNew function (Inside the Choral model) though so that i can fetch the choralId from there... Not sure if this is the best way to do it.***
- Users input a name for the device and a sample rate.

**Comment by cpjk** [comment]
Done
