### ISSUE TITLE
Design storyboard

### ISSUE THREAD

**Issue by jboretsky** [ChoralCloud/ChoralWeb#20]
It would be nice to have a storyboard that we can actually use so that everyone has the same rough idea of what the UI and flow is going to be like.

Please add ideas about UI or functionality here

**Comment by jboretsky** [comment]
![img_0229](https://user-images.githubusercontent.com/6702400/28235669-758af03c-68c7-11e7-82e2-3745d1adeead.JPG)

**Comment by andreirtaylor** [comment]
I think this is great. So long as the tabs beneath the graph are generated programatically even without the need for a custom defined chart as defined in #44. 

In my opinion this can be implemented with `Object.keys(data)`  [see here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) and creating a separate epoch chart for each of the keys. When new data comes in update the appropriate graph.

I also think that since we have bootstrap on the page that it would be really easy to make the charts toggle with [Dynamic Tabs](https://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp) as seen on that page.

**Comment by andreirtaylor** [comment]
@cpjk  @ecuellog what do you think?

**Comment by ecuellog** [comment]
I approve of this layout. So we should generate however many charts we have on the tabs... Not just the currently displayed one. Also, on the sidebar we could have the structures of the user's chorals so that it is easier to navigate through them.

**Comment by andreirtaylor** [comment]
I like the sidebar idea, but I think that is definitely a stretch goal and would need its own storyboard and design issue (@ecuellog please make an issue). I think something that should be essential is that you can click on the children chorals listed below to get to their graph view.

**Comment by cpjk** [comment]
I feel like this is pretty complex. 

Where are we storing the data for how to display each sub choral? On the choral data structures themselves?

I think it would be better to keep this simple, and have each chart display the data from its root choral. If you want to see the data from sub-chorals, create charts for them.

**Comment by andreirtaylor** [comment]
For the children I would just show their latest value.

**Comment by andreirtaylor** [comment]
And in the way I invision this the default way to view a graph would be the exact same for all chorals. Then the user is able to fine tune the way it is displayed using the charts function.

**Comment by cpjk** [comment]
how would a chart data structure fit in here then?

**Comment by cpjk** [comment]
Done?

**Comment by jboretsky** [comment]
Think so
