### ISSUE TITLE
Add children to a choral

### ISSUE THREAD

**Issue by andreirtaylor** [ChoralCloud/ChoralWeb#51]
We have the backend code to add children we just need a interface to actually update the choral and save the children to a choral.

**Comment by ecuellog** [comment]
Page to add children was added and works. Currently user just selects a parent choral and a child choral from a list of all the chorals available.
For future implementation: 
- User selects a choral from the View Chorals page ("Add Child" button) and this will redirect to 
/chorals/<choralId>/addChild 
instead of 
/children/new

- children.js routes will be moved to choral.js routes

**Comment by andreirtaylor** [comment]
#88

**Comment by cpjk** [comment]
done
